# Generated by Django 2.2.11 on 2020-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='start',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
